blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Dokumentace
    url: https://github.com/Cmajda/ha_cez_distribuce/tree/main/docs
    about: PÅ™ed vytvoÅ™enÃ­m issue zkontrolujte dokumentaci
  - name: ğŸ’¬ Diskuze
    url: https://github.com/Cmajda/ha_cez_distribuce/discussions
    about: Pro obecnÃ© dotazy a diskuze pouÅ¾ijte GitHub Discussions
